### ISSUE TITLE
Horizontal and vertical scroll on cards

### ISSUE THREAD

**Issue by JClarky** [MrConorAE/english#2]
![image](https://user-images.githubusercontent.com/30245116/140442557-dfbf26ca-d1f4-4002-885c-bce480a42f6e.png)

Horizontal and vertical scroll bars appear on every single flashcard when they are not necessary.

**Comment by JClarky** [comment]
FIX: in .card span.back delete overflow: scroll;

**Comment by MrConorAE** [comment]
Fixed by changing it to `overflow-y: scroll`.
